# Generated by Django 4.0.3 on 2022-04-08 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.IntegerField(default=1)),
                ('numero_materiales', models.IntegerField(default=1)),
                ('nombre_director_th', models.CharField(default='Soc.Ramiro Michelena Ch.', max_length=60)),
            ],
            options={
                'verbose_name_plural': '1. Configuración',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('jefe_inmediato', models.CharField(max_length=100)),
                ('director_th', models.CharField(default='Soc. Ramiro Michelena', max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(null=True)),
                ('fecha_entrada', models.DateField(null=True)),
                ('hora_salida', models.TimeField(null=True)),
                ('hora_entrada', models.TimeField(null=True)),
                ('cantidad_horas', models.IntegerField(default=0)),
                ('dias', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('particular', models.BooleanField(default=False)),
                ('calamidad_domestica', models.BooleanField(default=False)),
                ('enfermedad', models.BooleanField(default=False)),
                ('otros', models.BooleanField(default=False)),
                ('observaciones', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Permisos.funcionarios')),
            ],
            options={
                'verbose_name_plural': '3. Solicitudes de Permisos',
            },
        ),
    ]
