# Generated by Django 4.0.3 on 2022-04-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='numero_solicitud',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
