# Generated by Django 4.0.3 on 2022-04-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0002_alter_solicitudpermiso_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
