# Generated by Django 4.0.3 on 2022-04-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0003_solicitudpermiso_otro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='cantidad_horas',
        ),
    ]
