# Generated by Django 4.0.3 on 2022-04-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0004_remove_solicitudpermiso_cantidad_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='cantidad_horas',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
