# Generated by Django 4.0.3 on 2022-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0005_solicitudpermiso_cantidad_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='cantidad_horas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
